# frontend stage
FROM node:19 as frontend

WORKDIR /app

ENV REACT_APP_API_BASEURL="http://<domain>/api"

ENV REACT_APP_DOMAIN="<domain>"

COPY ./frontend .

RUN npm install

RUN npm run build

# nginx stage
FROM nginx

COPY --from=frontend /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]