# frontend stage
FROM node:19 as frontend

WORKDIR /app

ENV REACT_APP_API_BASEURL="https://tweexicon.live/api"

ENV REACT_APP_DOMAIN="tweexicon.live"

COPY ./frontend .

RUN npm install

RUN npm run build

# nginx stage
FROM nginx

COPY --from=frontend /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

COPY ssl-bundle.crt /etc/ssl/ssl-bundle.crt

COPY server.key /etc/ssl/server.key

CMD ["nginx", "-g", "daemon off;"]