FROM nginx

COPY frontend/build /usr/share/nginx/html

COPY nginx.conf.template /etc/nginx/nginx.conf.template

COPY webserver-docker-entrypoint.sh /script/

RUN chmod +x /script/webserver-docker-entrypoint.sh

ENTRYPOINT ["/script/webserver-docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]