version: '2'

services:
  backend:
    image: melhaouari/tweexicon-backend:master
    env_file:
      - .env.backend
    expose:
      - 3000
  webserver:
    image: melhaouari/tweexicon-webserver:master
    depends_on:
      - backend
    env_file:
      - .env.webserver
    volumes:
      - /root/ssl/certs/live/tweexicon.live:/etc/ssl
      - /root/ssl/certs/archive/tweexicon.live:/archive/tweexicon.live
    ports:
      - "443:443"
