version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env.backend
    expose:
      - 3000
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    depends_on:
      - backend
    ports:
      - "80:80"
