name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
      CONNECTION_STRING: mongodb://127.0.0.1:27017/tweexicon?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.0
      PORT: 3000
      PASSWORD_SALT: "d0a7f2e1b9c4a8d3"
      JWT_SECRET: "9f1b5e3d8a2c7f6b"
      JWT_VALIDITY: "1d"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: backend

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: npm install

    - name: Lint backend
      run: npm run lint

    - name: Run tests
      run: npm test

  frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: frontend

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: npm install

    - name: Lint frontend
      run: npm run lint
